site: Sidey
url: http://akittoe.github.io/sidey/ #yoururl
title: By AK
description: Simple and minimalistic jekyll blogging theme.
twitter: 
  username: adjoakittoe #yourusername
  card: summary
  creator: adjoakittoe #yourusername
author:
  twitter: #yourusername
  name: #yourusername
  avatar:
  email: #youremail
  url: http://akittoe.github.io/sidey/ #yoururl
permalink: pretty

baseurl: "http://akittoe.github.io/"

highlighter: none

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap  

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
